### ISSUE TITLE
TestMultiRunningServers fails

### ISSUE THREAD

**Issue by gavv** [iris-contrib/tests#3]
Hi, `TestMultiRunningServers` fails for me.

Command:

```
GOTRACEBACK=1 go test . |& pp
```

Output:

```
listen tcp4 65.254.242.180:8080: bind: cannot assign requested address
panic: listen tcp4 65.254.242.180:8080: bind: cannot assign requested address

FAIL    github.com/iris-contrib/tests   0.130s
1: running [Created by tests.TestMultiRunningServers @ server_test.go:26]
              panic.go:464      panic(0xa725e0, #1)
    logger    logger.go:129     (*Logger).Panic(*Logger(0xc8203a4660), interface{}(0xa725e0))
    iris      iris.go:169       (*Framework).Must(*Framework(#2), error(0x7f160f48f158))
    iris      iris.go:270       (*Framework).ListenTLS(*Framework(#2), string(0xc82029c5e0, len=17
), string(0xce1f80, len=11), string(0xce1fb0, len=9))                                            
14: select [Created by websocket.newServer @ server.go:77]
    websocket server.go:129     (*server).serve(*)
1: chan receive [Created by testing.RunTests @ testing.go:582]
    tests     server_test.go:34 TestMultiRunningServers(#22)
    testing   testing.go:473    tRunner(*T(#22), *InternalTest(#4))
1: sleep [Created by fasthttp.init.1 @ header.go:1372]
    time      time.go:59        Sleep(#5)
    fasthttp  header.go:1369    init.1.func1()
1: syscall [locked]
    runtime   asm_amd64.s:1998  goexit()
1: chan receive
    testing   testing.go:583    RunTests(0xe351d0, #3, 0xe, 0xe, #19)
    testing   testing.go:515    (*M).Run(*M(#6), 0x1d)
    main      _testmain.go:80   main()
```

/link gavv/httpexpect#13

**Comment by kataras** [comment]
Yes, if you use linux you have to edit the ` /etc/hosts`  and add this line:
`127.0.0.1 	mydomain.com` 
and run with root access ( until on my machine) this is how is working
```sh
$ su
$ go test -v 
``` 
(I am moving the tests on the kataras/iris again in order to have gocover support, I don't know how can I achieve gocover if I keep the tests here, if you know please tell me I searched but nothing comes up..)

**Comment by gavv** [comment]
Uh, it's odd. I think running tests should not require editing anything on the system, they should just run.

> I don't know how can I achieve gocover if I keep the tests here

AFAIK there is no (sane) way to archive this, currently.

**Comment by gavv** [comment]
Also it's not very convenient to create files in current directory (which is the source directory). I would rather use `ioutil.TemFile`.

**Comment by kataras** [comment]
Yes, or a virtual file system, I though it too but you know, I'm just testing the tests so far, I try to learn the httpexpect in few words, and about the first comment you're totally right, users should not require any action on their systems to run the tests, maybe I can add a t.Skip there, I want my tests to be realistic, but again maybe I will change that and use two handlers and compare their url's we will see
